name: build-zip
on:
  push:
    tags: ['v*']

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build plugin zip
        run: |
          VERSION=${GITHUB_REF_NAME}
          git archive --format=zip --prefix=ovesio/ -o ovesio-${VERSION}.zip HEAD

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ovesio-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}