name: build-plugin-zip
on:
  release:
    types: [published]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set vars
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build zip with folder prefix
        run: |
          PLUGIN=ovesio
          mkdir $PLUGIN
          rsync -a ./ $PLUGIN/ --exclude '.git*' --exclude '.github'
          zip -r ${PLUGIN}-${VERSION}.zip $PLUGIN

      - name: Upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: ovesio-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}